name: Deploy whatsoverhead to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Change to backend directory
      - name: Change directory to backend
        working-directory: backend
        run: echo "Switched to backend directory"

      # Step 3: Load .env variables (if needed)
      - name: Load environment variables from .env
        working-directory: backend
        run: |
          export $(cat .env | xargs)

      # Step 4: Authenticate with GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # Step 5: Build the Docker image
      - name: Build Docker image
        working-directory: backend
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ENDPOINT }} .

      # Step 6: Push the Docker image
      - name: Push Docker image
        working-directory: backend
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ENDPOINT }}

      # Step 7: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud beta run deploy ${{ secrets.ENDPOINT }} \
            --region ${{ secrets.CLOUDRUN_REGION }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.ENDPOINT }} \
            --port ${{ secrets.PORT }} \
            --cpu ${{ secrets.CLOUDRUN_CPU }} \
            --memory ${{ secrets.CLOUDRUN_MEMORY }}Gi \
            --max-instances ${{ secrets.CLOUDRUN_MAXINSTANCES }} \
            --concurrency ${{ secrets.CLOUDRUN_CONCURRENCY }} \
            --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }} \
            --allow-unauthenticated
